import { Providers } from "./providers";
import type { Metadata } from "next";
import { fontInter, fontPoppins } from "./font";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={(cn("font-inter"), fontInter.variable, fontPoppins.variable)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
